spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/aliapp?useSSL=false&useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 10  #初始化时建立物理连接的个数
      min-idle: 10  #最小连接池数量
      max-active: 500 #最大连接池数量 maxIdle已经不再使用
      max-wait: 60000 #获取连接时最大等待时间，单位毫秒
      test-while-idle: true #申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
      time-between-eviction-runs-millis: 60000  #既作为检测的间隔时间又作为testWhileIdel执行的依据
      min-evictable-idle-time-millis: 30000 #销毁线程时检测当前连接的最后活动时间和当前时间差大于该值时，关闭当前连接
      #用来检测连接是否有效的sql 必须是一个查询语句
      #mysql中为 select 'x'
      #oracle中为 select 1 from dual
      validation-query: select 'x'
      test-on-borrow: false #申请连接时会执行validationQuery检测连接是否有效,开启会降低性能,默认为true
      test-on-return: false #归还连接时会执行validationQuery检测连接是否有效,开启会降低性能,默认为true
      exception-sorter: true  #当数据库抛出不可恢复的异常时,抛弃该连接
      pool-prepared-statements: true  #是否缓存preparedStatement,mysql5.5+建议开启
      max-pool-prepared-statement-per-connection-size: 20 #当值大于0时poolPreparedStatements会自动修改为true

  #    模板配置
  thymeleaf:
    cache: false
    prefix: classpath:templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    content-type: text/html
  web:
    resources:
      chain:
        strategy:
          content:
            enabled: true
            paths: /**
      static-locations: classpath:static/
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

#Tomcat
server:
  port: 80
  ssl:
    key-store: classpath:static/ssl/server.jks
    key-store-password: 123456
    key-store-type: JKS
    key-alias: server
  tomcat:
    uri-encoding: UTF-8
    #最大链接数
    max-connections: 10000
    #最大等待队列长度
    accept-count: 1000
    #链接建立超时时间 ms
    connection-timeout: 30000
    #线程
    threads:
      #最小线程数
      min-spare: 100
      #最大线程数
      max: 2500

  #日志
  #logging:
  #  pattern:
  #    #设置日志等级
  #    level: DEBUG
  #    #设置输出日期格式
  #    dateformat: yyyy年MM月dd日HH:mm:ss
  #  #把日志输出到log/mylog.log文件中，这是相对路径，也可以用绝对路径
  #  file:
  #    path: log

  #spring:
  #  datasource:
  #    driver-class-name: com.mysql.jdbc.Driver
  #    url: jdbc:mysql://bdm698834178.my3w.com:3306/aliapp?useSSL=false&useUnicode=true&characterEncoding=utf8
  #    username: bdm698834178
  #    password: 198982Zhou